# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-21 16:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='KakaoPlusFriendMessage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_key', models.TextField()),
                ('type', models.TextField()),
                ('content', models.TextField()),
            ],
        ),
    ]
