# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-20 14:35
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('classMapInfo', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='DaumMapInfo',
            new_name='classMapInfo',
        ),
    ]
