# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-21 16:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classMapInfo', '0002_auto_20170620_2335'),
    ]

    operations = [
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='MessageButton',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.TextField()),
                ('url', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Photo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.TextField()),
                ('width', models.TextField()),
                ('height', models.TextField()),
            ],
        ),
        migrations.AddField(
            model_name='classmapinfo',
            name='danceHallName',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
    ]
